# Generated by Django 5.2.7 on 2025-10-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CTCFSite',
            fields=[
                ('site_id', models.AutoField(primary_key=True, serialize=False)),
                ('species_id', models.CharField(db_index=True, max_length=50)),
                ('chrom', models.CharField(db_index=True, max_length=50)),
                ('start', models.IntegerField(db_index=True)),
                ('end', models.IntegerField(db_index=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('motif_p', models.FloatField(blank=True, null=True)),
                ('cons_class', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'ctcf_sites',
            },
        ),
        migrations.CreateModel(
            name='Enhancer',
            fields=[
                ('enh_id', models.AutoField(primary_key=True, serialize=False)),
                ('species_id', models.CharField(db_index=True, max_length=50)),
                ('chrom', models.CharField(db_index=True, max_length=50)),
                ('start', models.IntegerField(db_index=True)),
                ('end', models.IntegerField(db_index=True)),
                ('tissue', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'enhancers_all',
            },
        ),
        migrations.CreateModel(
            name='EnhancerClass',
            fields=[
                ('enh_id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('class_name', models.CharField(db_column='class', db_index=True, max_length=50)),
            ],
            options={
                'db_table': 'enhancer_class',
            },
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('gene_id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=200)),
                ('species_id', models.CharField(db_index=True, max_length=50)),
                ('chrom', models.CharField(db_index=True, max_length=50)),
                ('start', models.IntegerField(db_index=True)),
                ('end', models.IntegerField(db_index=True)),
            ],
            options={
                'db_table': 'genes',
            },
        ),
        migrations.CreateModel(
            name='GWASSnp',
            fields=[
                ('snp_id', models.AutoField(primary_key=True, serialize=False)),
                ('chrom', models.CharField(db_index=True, max_length=50)),
                ('pos', models.IntegerField(db_index=True)),
                ('rsid', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('trait', models.CharField(blank=True, db_index=True, max_length=500, null=True)),
                ('pval', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'gwas_snps',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('species_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('genome_build', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'species',
            },
        ),
        migrations.CreateModel(
            name='TADDomain',
            fields=[
                ('tad_id', models.AutoField(primary_key=True, serialize=False)),
                ('species_id', models.CharField(db_index=True, max_length=50)),
                ('chrom', models.CharField(db_index=True, max_length=50)),
                ('start', models.IntegerField(db_index=True)),
                ('end', models.IntegerField(db_index=True)),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'tad_domains',
            },
        ),
        migrations.CreateModel(
            name='GeneToEnhancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_id', models.IntegerField(db_index=True)),
                ('enh_id', models.IntegerField(db_index=True)),
                ('method', models.CharField(blank=True, max_length=100, null=True)),
                ('distance_bp', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gene_to_enhancer',
                'unique_together': {('gene_id', 'enh_id')},
            },
        ),
        migrations.CreateModel(
            name='SnpToEnhancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snp_id', models.IntegerField(db_index=True)),
                ('enh_id', models.IntegerField(db_index=True)),
                ('overlap_bp', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'snp_to_enhancer',
                'unique_together': {('snp_id', 'enh_id')},
            },
        ),
    ]
