# Generated by Django 5.2.7 on 2025-10-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regland_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneExpression',
            fields=[
                ('expression_id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=200)),
                ('tissue', models.CharField(db_index=True, max_length=200)),
                ('tpm', models.FloatField()),
            ],
            options={
                'db_table': 'gene_expression',
                'indexes': [models.Index(fields=['symbol', 'tissue'], name='gene_expres_symbol_f6a015_idx')],
                'unique_together': {('symbol', 'tissue')},
            },
        ),
    ]
